/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CassetteComponent {
    }
}
declare global {
    interface HTMLCassetteComponentElement extends Components.CassetteComponent, HTMLStencilElement {
    }
    var HTMLCassetteComponentElement: {
        prototype: HTMLCassetteComponentElement;
        new (): HTMLCassetteComponentElement;
    };
    interface HTMLElementTagNameMap {
        "cassette-component": HTMLCassetteComponentElement;
    }
}
declare namespace LocalJSX {
    interface CassetteComponent {
    }
    interface IntrinsicElements {
        "cassette-component": CassetteComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cassette-component": LocalJSX.CassetteComponent & JSXBase.HTMLAttributes<HTMLCassetteComponentElement>;
        }
    }
}
